### ISSUE TITLE
conectare la kafkaimposibila pe mac

### ISSUE THREAD

**Issue by rredpoppy** [gov-ithub/asistentul_cetateanului_docker_dev_env#4]
docker e instalat, kitematic instalat, folosesc cli pentru compose, postgres pare sa fie in regula insa conectarea la kafka pica avand eroarea:

```
kafka_1      | [2016-12-04 08:01:30,704] WARN Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
kafka_1      | java.net.ConnectException: Connection refused
kafka_1      | 	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
kafka_1      | 	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
kafka_1      | 	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
kafka_1      | 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
kafka_1      | [2016-12-04 08:01:31,812] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
kafka_1      | [2016-12-04 08:01:31,814] WARN Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
kafka_1      | java.net.ConnectException: Connection refused
kafka_1      | 	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
kafka_1      | 	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
kafka_1      | 	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
kafka_1      | 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
```

**Comment by catta** [comment]
La prima vedere pare ca e o problema de publicare a porturilor de catre docker. Pentru a valida portul iti sugerez sa incerci sa faci telnet pe localhost port 2181. Daca telnetul se conecteaza atunci ai o problema in serverul care ruleaza in docker care iti refuza conecxiunea. Daca telnetul nu se conecteaza atunci as incerca prima data sa fac telnet pe ip-ul pe care este publicat docker (daca nu ma insel automat este 192.168.100.99). Toate informatiile astea le gasesti in consola cand pornesti imaginea docker. In final este posibil ca portul pe care vrei tu sa te conectezi sa nu fie publicat deloc de docker.

Cam astea sunt optiunile pe care le vad eu nefiind in cunostinta de cauza de proiect.
